repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args:
          - --cache
          - --cache-location=.prettier-cache
          - --ignore-path=.gitignore
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        alias: clippy-no-features
        name: clippy-no-features
        args:
          [
            --,
            -D,
            warnings,
            -D,
            clippy::perf,
            -D,
            clippy::print_stdout,
            -D,
            clippy::explicit_iter_loop,
            -D,
            clippy::uninlined_format_args,
            -D,
            clippy::semicolon_if_nothing_returned,
          ]
      - id: clippy
        alias: clippy-tracing
        name: clippy-tracing
        args:
          [
            --features=tracing,
            --,
            -D,
            warnings,
            -D,
            clippy::perf,
            -D,
            clippy::print_stdout,
            -D,
            clippy::explicit_iter_loop,
            -D,
            clippy::uninlined_format_args,
            -D,
            clippy::semicolon_if_nothing_returned,
          ]
  - repo: https://github.com/mondeja/rust-pc-hooks
    rev: v1.2.0
    hooks:
      - id: cargo-machete
