name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pre-commit
      - name: Lint
        run: pre-commit run --all-files --show-diff-on-failure

  test-rust:
    name: Test Rust source
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        features:
          - []
          - [tracing]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ matrix.rust-toolchain }}-${{ join(matrix.features, ',') }}
      - name: Run
        if: matrix.features[0] != null
        run: cargo test -p svg-path-cst --features ${{ join(matrix.features, ',') }}
      - name: Run
        if: matrix.features[0] == null
        run: cargo test -p svg-path-cst

  test-release-crate:
    name: Test crate release
    needs: test-rust
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v --dry-run

  release-crate:
    name: Release crate
    if: startsWith(github.ref, 'refs/tags/')
    needs: test-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v
